import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const dataDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "../data");
export const databasePath = resolve(dataDirectory, "db.json");

export async function readDatabase() {
  const contents = await readFile(databasePath, "utf8");
  return JSON.parse(contents);
}

export async function writeDatabase(database) {
  await writeFile(databasePath, `${JSON.stringify(database, null, 2)}\n`, "utf8");
  return database;
}

export async function findUserById(id) {
  const database = await readDatabase();
  return database.users.find((user) => user.id === id) || null;
}

export const activities = {
  math: {
    id: "math",
    subject: "Matemáticas",
    title: "Matemáticas - Reto Espacial",
    level: "Nivel 3",
    icon: "🚀",
    progressLabel: "Preguntas de exploración",
    questions: [
      { id: 1, question: "¿Cuánto es 7 + 5?", helperText: "Cuenta los ositos y alienígenas espaciales.", options: ["10", "12", "11", "13"], correctAnswer: "12", explanation: "7 ositos + 5 alienígenas = 12 amigos.", points: 10 },
      { id: 2, question: "¿Cuánto es 15 + 8?", helperText: "Suma las estrellas de cada equipo.", options: ["21", "22", "23", "24"], correctAnswer: "23", explanation: "15 + 8 = 23 estrellas.", points: 10 },
      { id: 3, question: "¿Cuánto es 14 - 6?", helperText: "Ayuda a los astronautas a volver a casa.", options: ["6", "7", "8", "9"], correctAnswer: "8", explanation: "Si quitamos 6 de 14, quedan 8.", points: 10 },
      { id: 4, question: "¿Cuánto es 20 - 9?", helperText: "Descubre cuántos planetas quedan.", options: ["10", "11", "12", "13"], correctAnswer: "11", explanation: "20 - 9 = 11 planetas.", points: 10 },
      { id: 5, question: "¿Cuánto es 4 × 3?", helperText: "Hay 4 naves con 3 estrellas cada una.", options: ["7", "10", "12", "14"], correctAnswer: "12", explanation: "4 grupos de 3 forman 12.", points: 10 },
      { id: 6, question: "¿Cuánto es 6 × 2?", helperText: "Cada robot tiene 2 antenas.", options: ["8", "10", "12", "14"], correctAnswer: "12", explanation: "6 grupos de 2 son 12 antenas.", points: 10 },
      { id: 7, question: "¿Cuánto es 12 ÷ 3?", helperText: "Reparte los cristales en 3 cofres iguales.", options: ["3", "4", "5", "6"], correctAnswer: "4", explanation: "12 repartido entre 3 cofres da 4.", points: 10 },
      { id: 8, question: "¿Cuánto es 10 ÷ 2?", helperText: "Comparte 10 lunas entre 2 exploradores.", options: ["2", "4", "5", "6"], correctAnswer: "5", explanation: "10 dividido entre 2 es 5.", points: 10 },
      { id: 9, question: "¿Cuánto es 9 + 6?", helperText: "Reúne todas las gemas del mapa.", options: ["13", "14", "15", "16"], correctAnswer: "15", explanation: "9 + 6 = 15 gemas.", points: 10 },
      { id: 10, question: "¿Cuánto es 18 - 7?", helperText: "Último desafío: aterriza la nave.", options: ["9", "10", "11", "12"], correctAnswer: "11", explanation: "18 - 7 = 11.", points: 10 },
    ],
  },
  spanish: {
    id: "spanish",
    subject: "Español",
    title: "Palabras Mágicas",
    level: "Nivel 2",
    icon: "📖",
    progressLabel: "Reto de palabras y pistas",
    exercises: [
      {
        id: 1,
        type: "adivinanza",
        clue: "Fruta roja y dulce que crece en los árboles.",
        clueEmoji: "🍎",
        helperText: "Comienza con M y termina con A.",
        targetWord: "MANZANA",
        displayPattern: ["M", "_", "N", "Z", "_", "N", "A"],
        explanation: "¡La MANZANA es una fruta deliciosa y saludable!",
        points: 10,
      },
      {
        id: 2,
        type: "antonimo",
        clue: "Lo contrario de DÍA es...",
        clueEmoji: "🌙",
        helperText: "Cuando sale la luna y las estrellas.",
        targetWord: "NOCHE",
        displayPattern: ["N", "O", "_", "H", "E"],
        explanation: "¡El antónimo o contrario de día es NOCHE!",
        points: 10,
      },
      {
        id: 3,
        type: "sinonimo",
        clue: "Sinónimo de FELIZ; alguien que sonríe mucho está...",
        clueEmoji: "😊",
        helperText: "Tiene 6 letras y empieza con A.",
        targetWord: "ALEGRE",
        displayPattern: ["A", "_", "E", "G", "_", "E"],
        explanation: "¡ALEGRE significa lo mismo que feliz!",
        points: 10,
      },
      {
        id: 4,
        type: "adivinanza",
        clue: "Animal fiel de cuatro patas que ladra y cuida la casa.",
        clueEmoji: "🐶",
        helperText: "El mejor amigo del explorador.",
        targetWord: "PERRO",
        displayPattern: ["P", "E", "_", "_", "O"],
        explanation: "¡El PERRO es el animal más leal y cariñoso!",
        points: 10,
      },
      {
        id: 5,
        type: "adivinanza",
        clue: "El astro rey que nos da luz y calor todos los días.",
        clueEmoji: "☀️",
        helperText: "Palabra corta de 3 letras.",
        targetWord: "SOL",
        displayPattern: ["S", "_", "L"],
        explanation: "¡El SOL es la estrella central de nuestro sistema!",
        points: 10,
      },
      {
        id: 6,
        type: "sinonimo",
        clue: "Sinónimo de HERMOSO o lindo.",
        clueEmoji: "🌸",
        helperText: "Empieza con B y rima con destello.",
        targetWord: "BELLO",
        displayPattern: ["B", "E", "_", "_", "O"],
        explanation: "¡BELLO es una palabra que describe algo muy bonito!",
        points: 10,
      },
      {
        id: 7,
        type: "antonimo",
        clue: "Lo contrario de GRANDE es...",
        clueEmoji: "🐜",
        helperText: "Como una diminuta hormiguita.",
        targetWord: "PEQUEÑO",
        displayPattern: ["P", "E", "Q", "_", "E", "Ñ", "_"],
        explanation: "¡El antónimo de grande es PEQUEÑO!",
        points: 10,
      },
      {
        id: 8,
        type: "adivinanza",
        clue: "Tiene portada, hojas de papel y cuenta historias fascinantes.",
        clueEmoji: "📖",
        helperText: "Lo abres para leer y aprender.",
        targetWord: "LIBRO",
        displayPattern: ["L", "I", "_", "R", "_"],
        explanation: "¡Un LIBRO abre las puertas a mundos mágicos!",
        points: 10,
      },
      {
        id: 9,
        type: "adivinanza",
        clue: "Medio de transporte con alas que vuela alto por las nubes.",
        clueEmoji: "✈️",
        helperText: "Lleva pasajeros por los cielos.",
        targetWord: "AVION",
        displayPattern: ["A", "V", "_", "_", "N"],
        explanation: "¡El AVIÓN cruza continentes y océanos volando!",
        points: 10,
      },
      {
        id: 10,
        type: "adivinanza",
        clue: "Brilla en el cielo nocturno y guía a los navegantes.",
        clueEmoji: "⭐",
        helperText: "Pide un deseo cuando veas una fugaz.",
        targetWord: "ESTRELLA",
        displayPattern: ["E", "S", "T", "_", "E", "L", "_", "A"],
        explanation: "¡Las ESTRELLAS iluminan todo el universo infinito!",
        points: 10,
      },
    ],
  },
  science: {
    id: "science",
    subject: "Ciencias",
    title: "Ciencias Naturales",
    headline: "✨ ¡Ordena los procesos de la naturaleza! ✨",
    level: "Nivel 4",
    icon: "🌱",
    progressLabel: "Ciclos de la naturaleza",
    exercises: [
      {
        id: 1,
        title: "Ciclo de Vida de la Planta",
        instruction: "Ordena los pasos desde la siembra hasta florecer:",
        icon: "🌱",
        items: [
          { id: "seed", label: "Semilla bajo tierra", emoji: "🌰" },
          { id: "sprout", label: "Brote verde", emoji: "🌱" },
          { id: "plant", label: "Planta con hojas", emoji: "🌿" },
          { id: "flower", label: "Flor colorida", emoji: "🌸" },
        ],
        correctOrder: ["seed", "sprout", "plant", "flower"],
        explanation: "La semilla germina bajo tierra, surge un brote, crecen hojas y finalmente se abre una flor.",
        points: 10,
      },
      {
        id: 2,
        title: "Ciclo de la Mariposa",
        instruction: "Ordena la asombrosa metamorfosis de la mariposa:",
        icon: "🦋",
        items: [
          { id: "egg", label: "Diminuto huevo", emoji: "🥚" },
          { id: "caterpillar", label: "Oruga comelona", emoji: "🐛" },
          { id: "chrysalis", label: "Crisálida dormida", emoji: "🥥" },
          { id: "butterfly", label: "Hermosa mariposa", emoji: "🦋" },
        ],
        correctOrder: ["egg", "caterpillar", "chrysalis", "butterfly"],
        explanation: "Del huevo nace la oruga, luego se transforma dentro de la crisálida y emerge una mariposa.",
        points: 10,
      },
      {
        id: 3,
        title: "Ciclo del Agua",
        instruction: "Ordena el viaje que hace el agua por el planeta:",
        icon: "💧",
        items: [
          { id: "evap", label: "El sol calienta y evapora", emoji: "☀️" },
          { id: "cond", label: "Se forman nubes en el cielo", emoji: "☁️" },
          { id: "precip", label: "Cae la lluvia fresca", emoji: "🌧️" },
          { id: "collect", label: "Llega a ríos y océanos", emoji: "🌊" },
        ],
        correctOrder: ["evap", "cond", "precip", "collect"],
        explanation: "El calor evapora el agua, forma nubes por condensación, llueve y regresa a los ríos y mares.",
        points: 10,
      },
      {
        id: 4,
        title: "Ciclo del Día y la Noche",
        instruction: "Ordena los momentos de un día solar completo:",
        icon: "☀️",
        items: [
          { id: "dawn", label: "Amanecer dorado", emoji: "🌅" },
          { id: "noon", label: "Mediodía radiante", emoji: "☀️" },
          { id: "sunset", label: "Atardecer naranja", emoji: "🌇" },
          { id: "night", label: "Noche estrellada", emoji: "🌙" },
        ],
        correctOrder: ["dawn", "noon", "sunset", "night"],
        explanation: "La rotación de la Tierra nos lleva del amanecer al mediodía, luego atardece y llega la noche.",
        points: 10,
      },
      {
        id: 5,
        title: "Cadena Alimenticia",
        instruction: "¿Quién se alimenta de quién en la naturaleza?:",
        icon: "🌾",
        items: [
          { id: "plant", label: "Planta productora", emoji: "🌾" },
          { id: "insect", label: "Saltamontes herbívoro", emoji: "🦗" },
          { id: "frog", label: "Rana carnívora", emoji: "🐸" },
          { id: "eagle", label: "Águila rapaz", emoji: "🦅" },
        ],
        correctOrder: ["plant", "insect", "frog", "eagle"],
        explanation: "La planta produce alimento, el saltamontes la come, la rana caza al saltamontes y el águila a la rana.",
        points: 10,
      },
      {
        id: 6,
        title: "Ciclo de la Rana",
        instruction: "Ordena cómo crece este pequeño anfibio:",
        icon: "🐸",
        items: [
          { id: "eggs", label: "Huevos en el agua", emoji: "🫧" },
          { id: "tadpole", label: "Renacuajo con cola", emoji: "🐟" },
          { id: "froglet", label: "Renacuajo con patitas", emoji: "🦎" },
          { id: "adult_frog", label: "Rana saltarina", emoji: "🐸" },
        ],
        correctOrder: ["eggs", "tadpole", "froglet", "adult_frog"],
        explanation: "Los huevitos eclosionan en renacuajos nadadores, desarrollan patas traseras y crecen como ranas.",
        points: 10,
      },
      {
        id: 7,
        title: "Estados del Agua",
        instruction: "Ordena los cambios al aumentar la temperatura:",
        icon: "🧊",
        items: [
          { id: "solid", label: "Hielo sólido frío", emoji: "🧊" },
          { id: "liquid", label: "Agua líquida templada", emoji: "💧" },
          { id: "gas", label: "Vapor caliente gaseoso", emoji: "💨" },
        ],
        correctOrder: ["solid", "liquid", "gas"],
        explanation: "Al calentarse, el hielo se derrite en agua líquida y al hervir se convierte en vapor invisible.",
        points: 10,
      },
      {
        id: 8,
        title: "Cadena del Reciclaje",
        instruction: "Ordena el proceso para reutilizar materiales:",
        icon: "♻️",
        items: [
          { id: "sort", label: "Separar residuos limpios", emoji: "🗑️" },
          { id: "truck", label: "Camión recolector", emoji: "🚛" },
          { id: "factory", label: "Fábrica procesadora", emoji: "🏭" },
          { id: "product", label: "Nuevo objeto reciclado", emoji: "📦" },
        ],
        correctOrder: ["sort", "truck", "factory", "product"],
        explanation: "Separamos materiales, el camión los lleva a la fábrica y se crean nuevos productos sin talar árboles.",
        points: 10,
      },
      {
        id: 9,
        title: "Germinación de la Semilla",
        instruction: "Ordena el despertar de una semilla:",
        icon: "🌰",
        items: [
          { id: "seed_wet", label: "Semilla absorbe humedad", emoji: "🌰" },
          { id: "roots", label: "Crecen raíces hacia abajo", emoji: "🪴" },
          { id: "stem", label: "El tallo emerge a la luz", emoji: "🌱" },
          { id: "leaves", label: "Se abren hojas verdes", emoji: "🌿" },
        ],
        correctOrder: ["seed_wet", "roots", "stem", "leaves"],
        explanation: "El agua despierta la semilla, primero echa raíces para anclarse y luego saca su tallo hacia el sol.",
        points: 10,
      },
      {
        id: 10,
        title: "El Viaje de la Semilla",
        instruction: "Ordena cómo viajan las semillas para sembrar bosques:",
        icon: "🍎",
        items: [
          { id: "fruit", label: "Fruto dulce maduro", emoji: "🍎" },
          { id: "bird", label: "Ave come la fruta", emoji: "🐦" },
          { id: "drop", label: "Semilla cae en tierra fértil", emoji: "🍂" },
          { id: "new_tree", label: "Nace un nuevo arbolito", emoji: "🌲" },
        ],
        correctOrder: ["fruit", "bird", "drop", "new_tree"],
        explanation: "Las aves comen fruta madura y dispersan las semillas lejos, ayudando a que nazcan nuevos árboles.",
        points: 10,
      },
    ],
  },
  geography: {
    id: "geography",
    subject: "Geografía",
    title: "Mundo Explorador",
    level: "Nivel 1",
    icon: "🌐",
    progressLabel: "Desafío de continentes y lugares",
    questions: [
      {
        id: 1,
        question: "¿Cuál es el océano más grande y profundo del planeta Tierra?",
        helperText: "Cubre más de un tercio de toda la superficie del planeta.",
        options: ["Océano Atlántico", "Océano Pacífico", "Océano Índico", "Océano Ártico"],
        correctAnswer: "Océano Pacífico",
        explanation: "¡El Océano Pacífico es tan inmenso que en él cabrían todos los continentes juntos!",
        points: 10,
      },
      {
        id: 2,
        question: "¿En qué país se encuentran las famosas Pirámides y la Gran Esfinge de Guiza?",
        helperText: "Tierra milenaria bañada por el río Nilo.",
        options: ["México", "Italia", "Egipto", "China"],
        correctAnswer: "Egipto",
        explanation: "¡Egipto es el hogar de las pirámides construidas por los antiguos faraones!",
        points: 10,
      },
      {
        id: 3,
        question: "¿Por cuál de los cuatro puntos cardinales sale el Sol cada mañana?",
        helperText: "Señala hacia donde amanece el nuevo día.",
        options: ["Norte", "Sur", "Este", "Oeste"],
        correctAnswer: "Este",
        explanation: "¡El Sol siempre aparece por el Este debido al giro de rotación de la Tierra!",
        points: 10,
      },
      {
        id: 4,
        question: "¿Cuál de estos planetas del Sistema Solar es conocido como el 'Planeta Rojo'?",
        helperText: "Tiene polvo rojizo y dos pequeñas lunas llamadas Fobos y Deimos.",
        options: ["Venus", "Marte", "Júpiter", "Saturno"],
        correctAnswer: "Marte",
        explanation: "¡Marte es rojo porque su suelo es rico en óxido de hierro, como el metal rojizo!",
        points: 10,
      },
      {
        id: 5,
        question: "¿Cuál es la montaña más alta del planeta Tierra sobre el nivel del mar?",
        helperText: "Se encuentra en la majestuosa cordillera del Himalaya.",
        options: ["Monte Everest", "Monte Fuji", "Aconcagua", "Kilimanjaro"],
        correctAnswer: "Monte Everest",
        explanation: "¡El Monte Everest mide casi 8,849 metros de altura rozando el cielo!",
        points: 10,
      },
      {
        id: 6,
        question: "¿Cuál es el desierto cálido más grande del mundo?",
        helperText: "Cubre gran parte del norte del continente africano.",
        options: ["Desierto de Atacama", "Desierto de Gobi", "Desierto del Sahara", "Desierto de Sonora"],
        correctAnswer: "Desierto del Sahara",
        explanation: "¡El Sahara es un inmenso mar de dunas doradas en el norte de África!",
        points: 10,
      },
      {
        id: 7,
        question: "¿Cuál es el río más largo y caudaloso del planeta Tierra?",
        helperText: "Atraviesa la mayor selva tropical en América del Sur.",
        options: ["Río Nilo", "Río Amazonas", "Río Misisipi", "Río Danubio"],
        correctAnswer: "Río Amazonas",
        explanation: "¡El río Amazonas vierte más agua al océano que cualquier otro río del mundo!",
        points: 10,
      },
      {
        id: 8,
        question: "¿En qué clima hace mucho frío todo el año y el suelo está cubierto de hielo?",
        helperText: "El hábitat de osos polares y pingüinos.",
        options: ["Clima Desértico", "Clima Tropical", "Clima Polar", "Clima Templado"],
        correctAnswer: "Clima Polar",
        explanation: "¡Los climas polares en el Ártico y la Antártida tienen hielo y nieve perpetua!",
        points: 10,
      },
      {
        id: 9,
        question: "¿Cómo se llama la línea imaginaria que divide la Tierra en Hemisferio Norte y Sur?",
        helperText: "Recibe la luz del Sol perpendicularmente todo el año.",
        options: ["Trópico de Cáncer", "Meridiano de Greenwich", "Ecuador", "Círculo Polar"],
        correctAnswer: "Ecuador",
        explanation: "¡La línea del Ecuador es el cinturón imaginario que rodea el centro de la Tierra!",
        points: 10,
      },
      {
        id: 10,
        question: "¿Qué inmensa selva sudamericana es considerada el 'pulmón del planeta' por su biodiversidad?",
        helperText: "Hogar de miles de especies únicas de plantas y animales.",
        options: ["Selva Negra", "Selva Amazónica", "Bosque Boreal", "Selva del Congo"],
        correctAnswer: "Selva Amazónica",
        explanation: "¡La Selva Amazónica genera gran parte del oxígeno y alberga una biodiversidad inigualable!",
        points: 10,
      },
    ],
  },
};

export const dailyChallenge = {
  id: "daily-space-mission",
  title: "Misión Espacial Secreta",
  description: "Resuelve 5 desafíos para ganar un super cofre misterioso con 100 gemas galácticas.",
  total: 5,
};
